# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLOGINWITHGOOGLE():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_lOGINWITHGOOGLE(self):
    self.driver.get("https://open.spotify.com/")
    self.driver.set_window_size(784, 864)
    self.driver.find_element(By.CSS_SELECTOR, ".LKFFk88SIRC9QKKUWR5u .e-9921-baseline").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".LKFFk88SIRC9QKKUWR5u .e-9921-baseline")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".sc-iXqmyu:nth-child(1) > .Button-sc-y0gtbx-0").click()
    self.driver.find_element(By.CSS_SELECTOR, ".aZvCDf:nth-child(1) .yAlK0b").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ButtonInner-sc-14ud5tc-0").click()
  
